env:
  global:
    - CC_TEST_REPORTER_ID=f7efd3a2042631e5810ec00089e8b1ef1a148f2a3546ea9f6aa653291d9dab27

language: ruby

cache: bundler

rvm:
  - 2.5.1

services:
  - postgresql

notifications:
  - false

before_script:  
  - cp config/database.yml.travis config/database.yml 
  - psql -c 'create database TaskPlanify_test;' -U postgres      
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT