language: ruby

rvm:
 - 2.5.1

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
 
before_install: gem install bundler -v 1.16.1

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec minitest test/

before_script:  
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml  

bundler_args: --binstubs=./bundler_stubs