language: ruby
rvm:
 - 2.5.1
 addons:
 - postgresql: 10.0
before_install: gem install bundler -v 1.16.1
before_script:  
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres