language: ruby

rvm:
 - 2.5.1

 env:
  - DB=pgsql
 
before_install: gem install bundler -v 1.16.1

before_script:  
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database TaskPlanify_test;' -U postgres