env:
  global:
    - CC_TEST_REPORTER_ID=f7efd3a2042631e5810ec00089e8b1ef1a148f2a3546ea9f6aa653291d9dab27

language: ruby

rvm:
 - 2.5.1

services:
  - postgresql

addons:
  postgresql: "10"  
 
before_install: gem install bundler -v 1.16.1

notifications:
  - false

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec minitest test/

before_script:  
  - psql -c 'create database travis_ci_test;' -U postgres   
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

bundler_args: --binstubs=./bundler_stubs