language: ruby

rvm:
 - 2.5.1

 env:
  - DB=postgresql
 
before_install: gem install bundler -v 1.16.1

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec minitest test/

before_script:  
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database TaskPlanify_test;' -U postgres

bundler_args: --binstubs=./bundler_stubs